packages:
  - template/base
  - template/config/**
  - template/formatting/**
  - template/linting/**
  - template/tsconfig/**

ignoredBuiltDependencies:
  - cypress
  - esbuild
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.1.15-alpha.7
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.15-alpha.7
  vite-plus: 0.1.15-alpha.7
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
